services:
  accounts:
    image: "salmagd/accounts:ms"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    mem_limit: 700m
    networks:
      - microbank

  loans:
    image: "salmagd/loans:ms"
    container_name: loans-ms
    ports:
      - "8090:8090"
    mem_limit: 700m
    networks:
      - microbank

  cards:
    image: "salmagd/cards:ms"
    container_name: cards-ms
    ports:
      - "9000:9000"
    mem_limit: 700m
    networks:
      - microbank

networks:
  microbank:
    driver: bridge